#include<iostream.h>
#include<conio.h>
  void main()
  {
       clrscr();
      float c,b,a;;
      cout<<"\n\n\n Enter any two number :";
      cin>>a>> b;
      c=a+b;
      cout<<" \n\n\n\nso addition is :";
      cout<<a<<"+"<<b<<"="<< c ;
      c=a-b;
      cout <<" so subtraction is :";
      cout<<a<<"-"<<b<<"="<<c;
	c=a*b;
	cout<<" so multipication is:";
	cout<<a<<"*"<<b<<"="<<c;
     c=a/b;
     cout<<" so division is:";
     cout<< a<<"/"<<b<<"="<<c;

      getch();
      }